# Generated by Django 4.2.16 on 2025-01-11 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_inviteteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteteam',
            name='found_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
