# Generated by Django 4.2.16 on 2025-01-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_book', to='records.book'),
        ),
    ]
