# Generated by Django 4.2.16 on 2025-01-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_chat_count_book_comment_count_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_id',
            field=models.IntegerField(default=-1),
        ),
    ]
