# Generated by Django 4.2.16 on 2025-01-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_comment_reply_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
