# Generated by Django 4.2.16 on 2025-01-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_book_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info_medium',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
