# Generated by Django 4.2.16 on 2025-04-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_book_info_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
