# Generated by Django 4.2.16 on 2025-01-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticmedia',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='staticmedia',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
